global:
  scrape_interval: 15s  # Scrape metrics every 15 seconds

scrape_configs:
  - job_name: 'producer'
    static_configs:
      - targets: ['10.23.0.111:9101']  # Producer app endpoint

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['10.23.0.111:9308']  # Kafka Exporter endpoint

  - job_name: 'consumer'
    static_configs:
      - targets: ['10.23.0.111:9103']  # Consumer app endpoint


